# Generated by Django 5.2 on 2025-05-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generate_files', '0002_alter_fichebesoins_designation'),
        ('invitation_offre', '0002_alter_invitationoffre_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiche_de_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_files.fichebesoins')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_offre.invitationoffre')),
            ],
            options={
                'db_table': 'invitation_fichiers',
            },
        ),
    ]
