# Generated by Django 5.2 on 2025-05-07 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_offre', models.IntegerField()),
                ('delai_offre', models.IntegerField()),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitations_offres',
            },
        ),
    ]
