# Generated by Django 5.2 on 2025-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.CharField(max_length=100)),
                ('rc', models.CharField(max_length=100)),
                ('compte_bancaire', models.CharField(max_length=100)),
            ],
        ),
    ]
