# Generated by Django 5.2 on 2025-05-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fournisseur',
            table='fournisseurs',
        ),
    ]
