# Generated by Django 5.2 on 2025-05-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '0001_initial'),
        ('devisglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.designation')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devisglobal.devisglobal')),
            ],
            options={
                'db_table': 'devisligne',
            },
        ),
    ]
