# Generated by Django 5.2 on 2025-05-16 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisligne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devisligne',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
