# Generated by Django 5.2 on 2025-05-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheBesoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.PositiveIntegerField()),
                ('observation', models.CharField(blank=True, max_length=150, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='designation.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fiche_besoin',
            },
        ),
    ]
