# Generated by Django 5.2 on 2025-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FicheBesoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('observation', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
