# Generated by Django 5.2 on 2025-05-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('generate_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichebesoins',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='designation.designation', unique=True),
        ),
    ]
