# Generated by Django 5.2 on 2025-04-22 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichebesoins',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichebesoins',
            name='observation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fichebesoins',
            name='quantité',
            field=models.PositiveIntegerField(),
        ),
    ]
