# Generated by Django 5.2 on 2025-04-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_files', '0002_fichebesoins_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fichebesoins',
            table='fichebesoins',
        ),
    ]
