# Generated by Django 5.2 on 2025-05-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches_besoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('observation', models.TextField(blank=True)),
                ('fiche_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='fiches_besoin.fichebesoin')),
            ],
            options={
                'db_table': 'besoin',
            },
        ),
    ]
