# Generated by Django 5.2 on 2025-05-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besoins', '0001_initial'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.designation'),
        ),
    ]
