# Generated by Django 5.2 on 2025-05-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devisglobal', '0002_devisglobal_piece_jointe_alter_devisglobal_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=100, unique=True)),
                ('date_bon', models.DateField()),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_commande', to='devisglobal.devisglobal')),
            ],
            options={
                'db_table': 'boncommandes',
            },
        ),
    ]
