# Generated by Django 5.2.1 on 2025-05-15 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisglobal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisglobal',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Téléversez une pièce jointe (photo ou PDF).', null=True, upload_to='devis_pieces/'),
        ),
        migrations.AlterField(
            model_name='devisglobal',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5),
        ),
    ]
