# Generated by Django 5.2 on 2025-05-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches_besoin', '0001_initial'),
        ('invitations_offre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationFicheBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiche_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_invitations', to='fiches_besoin.fichebesoin')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_fiches', to='invitations_offre.invitation')),
            ],
            options={
                'db_table': 'invitation_fiche_besoin',
                'unique_together': {('invitation', 'fiche_besoin')},
            },
        ),
    ]
