# Generated by Django 5.2 on 2025-05-12 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_fiche_besoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationfichebesoin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
