# Generated by Django 5.2 on 2025-05-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_fiche_besoin', '0002_invitationfichebesoin_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationfichebesoin',
            name='created_at',
        ),
    ]
