# Generated by Django 5.2 on 2025-05-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_offre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitationoffre',
            table='invitation_offre',
        ),
    ]
